executable('nfctool',
  'adapter.c',
  'display.c',
  'llcp-decode.c',
  'main.c',
  'ndef-decode.c',
  'netlink.c',
  'snep-decode.c',
  'sniffer.c',
  c_args              : tool_c_args,
  include_directories : [top_inc, src_inc],
  dependencies        : [glib_dep, netlink_dep, config_dep],
  install             : true,
)
