# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2021 Canonical Ltd.
# Author: Krzysztof Kozlowski <krzysztof.kozlowski@canonical.com>
#                             <krzk@kernel.org>
#
name: "CppCheck"
on: [push, pull_request]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install additional packages
      run: |
        sudo ./ci/ubuntu.sh
        sudo apt-get install -y cppcheck flawfinder

    # - name: 'Analysis with: Cppcheck'
    #   run: cppcheck --output-file=report-cppcheck.txt ./

    # - name: 'Analysis with: flawfinder'
    #  run: flawfinder --columns --context --singleline . > report-flawfinder.txt

    - name: Analysis
      run: ci/static-analysis.sh
